<?php
/**
 * Phoenix Cash on Delivery module for Magento 2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Mage
 * @package    Phoenix_CashOnDelivery
 * @copyright  Copyright (c) 2017 Phoenix Media GmbH (http://www.phoenix-media.eu)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/** @var \Phoenix\CashOnDelivery\Block\Adminhtml\Sales\Creditmemo\Create\Totals $this */
?>
<?php if ($this->getSource()): ?>
    <tr>
        <td class="label"><?php echo $this->getRefundLabel(); ?></td>
        <td><input type="text" name="creditmemo[cashondelivery_amount]" value="<?php echo $this->getCodAmount()?>" class="input-text admin__control-text not-negative-amount" id="cod_amount" /></td>
    </tr>
<?php endif; ?>
